spring.config.import=optional:file:./env.properties

spring.application.name=epicode-s7-spring-week-project-gestione-eventi
server.port=${PORT:8080}

# ==================== DATABASE CONFIGURATION (PostgreSQL) ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
#spring.datasource.url=jdbc:postgresql://localhost:15432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================== JPA/HIBERNATE CONFIGURATION ====================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

# ==================== JWT CONFIGURATION ====================
jwt.secret=${JWT_SECRET}
jwt.expirationms=${JWT_EXPIRATION_MS:86400000}

# ==================== SEED DATABASE ====================
app.seed.enabled=true